### ISSUE TITLE
Missing code coverage data results in file not found exception

### ISSUE THREAD

**Issue by rouke-broersma** [Faultify/Faultify#17]
For some reason the code coverage data was not properly generated. This resulted in a file not found exception.

```
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\git\endeavour-cloud\CloudApp\InfoSupport.PDC.Cloud.Authentication.Test\bin\Debug\net5.0\test-duplication-0\coverage.bin'.
File name: 'C:\git\endeavour-cloud\CloudApp\InfoSupport.PDC.Cloud.Authentication.Test\bin\Debug\net5.0\test-duplication-0\coverage.bin'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at Faultify.TestRunner.TestProcess.DotnetTestRunner.RunCodeCoverage(CancellationToken cancellationToken) in E:\programming\FaultifyNew\Faultify\Faultify.TestRunner\TestProcess\DotnetTestRunner.cs:line 156
   at Faultify.TestRunner.MutationTestProject.RunCoverage(String testAssemblyPath, CancellationToken cancellationToken) in E:\programming\FaultifyNew\Faultify\Faultify.TestRunner\MutationTestProject.cs:line 161
   at Faultify.TestRunner.MutationTestProject.Test(MutationSessionProgressTracker progressTracker, CancellationToken cancellationToken) in E:\programming\FaultifyNew\Faultify\Faultify.TestRunner\MutationTestProject.cs:line 77
   at Faultify.Cli.Program.RunMutationTest(Settings settings, MutationSessionProgressTracker progressTracker) in E:\programming\FaultifyNew\Faultify\Faultify.Cli\Program.cs:line 144
   at Faultify.Cli.Program.Run(Settings settings) in E:\programming\FaultifyNew\Faultify\Faultify.Cli\Program.cs:line 129
   at Faultify.Cli.Program.Main(String[] args) in E:\programming\FaultifyNew\Faultify\Faultify.Cli\Program.cs:line 76
   at Faultify.Cli.Program.<Main>(String[] args)
```

**Comment by TimonPost** [comment]
If the `coverage.bin` is not generated the process can not continue. For some reason, the code-coverage process did not finish correctly. I am currently investigating it since I have noted the same behavior.

**Comment by TimonPost** [comment]
For both test_results.bin and coverage.bin I want to print a special message to the console indicating something went wrong during the test process.
