### ISSUE TITLE
When no mutations can be generated a divide by zero exception is thrown

### ISSUE THREAD

**Issue by rouke-broersma** [Faultify/Faultify#21]
```
> [20%] Start Mutation Test Session:
| Test Rounds: 0
| Mutations Found: 0
| Worst Case Time: 0s
Unhandled exception. System.DivideByZeroException: Attempted to divide by zero.
   at Faultify.TestRunner.MutationSessionProgressTracker.LogEndTestSession(TimeSpan elapsed, Int32 completedTestRounds, Int32 mutationCount, Single score) in E:\programming\FaultifyNew\Faultify\Faultify.TestRunner\MutationSessionProgressTracker.cs:line 87
   at Faultify.TestRunner.MutationTestProject.StartMutationTestSession(TestProjectInfo testProjectInfo, Dictionary`2 testsPerMutation, MutationSessionProgressTracker sessionProgressTracker, CancellationToken cancellationToken, TimeSpan coverageTestRunTime, TestProjectDuplicationPool testProjectDuplicationPool) in E:\programming\FaultifyNew\Faultify\Faultify.TestRunner\MutationTestProject.cs:line 285
   at Faultify.TestRunner.MutationTestProject.Test(MutationSessionProgressTracker progressTracker, CancellationToken cancellationToken) in E:\programming\FaultifyNew\Faultify\Faultify.TestRunner\MutationTestProject.cs:line 82
   at Faultify.Cli.Program.RunMutationTest(Settings settings, MutationSessionProgressTracker progressTracker) in E:\programming\FaultifyNew\Faultify\Faultify.Cli\Program.cs:line 144
   at Faultify.Cli.Program.Run(Settings settings) in E:\programming\FaultifyNew\Faultify\Faultify.Cli\Program.cs:line 129
   at Faultify.Cli.Program.Main(String[] args) in E:\programming\FaultifyNew\Faultify\Faultify.Cli\Program.cs:line 76
   at Faultify.Cli.Program.<Main>(String[] args)
```

**Comment by TimonPost** [comment]
To fix this issue we need to make sure there is some kind of 0 check here: `MutationSessionProgressTracker.LogEndTestSession`
